# Generated by Django 4.2 on 2024-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lliga',
            name='temporada',
            field=models.CharField(default=-1, max_length=9),
            preserve_default=False,
        ),
    ]
